### ISSUE TITLE
CORS error when integrating with Swedish Bird Trends

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/dw-system#3]
The error is:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://birds.dina-web.net/species/3c42a44c-096a-445d-b574-22297e96373d.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*.dina-web.net’).

The solution may be provided by reconfiguring nginx and adding headers in another way:

http://serverfault.com/questions/384105/cross-origin-resource-sharing-cors-with-nginx-chrome

**Comment by Inkimar** [comment]
open to '*'
To test this , try Corvux Corax on naturforskaren.se
https://dina-web.net/naturalist/species/3c42a44c-096a-445d-b574-22297e96373d
The third icon in the far right column should display 'Fågeltrender'

**Comment by Inkimar** [comment]
moved to https://github.com/mskyttner/swedishbirdtrends/issues/1
